# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe0f5d9542b9113c952624a0424ec31564397effdc174b9051ab31ef6a941a1fb83e80d9f4a9d6a843d9c35c49f880f461e9e307de11aa2ae6e39c82f1af3714

test:
  secret_key_base: 487d28f43fcf8ce23b02b56dfac3c814b8cb032fcc31631e2896b6dc6214cbdceb2af0bde210604bb1dcf9510bdfce045252caf5ec555df8bb30dbc3a0f74c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
